# Generated by Django 5.2.4 on 2025-07-28 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=100)),
                ('instance_number', models.IntegerField(default=0)),
                ('file_path', models.FileField(upload_to='dicom_files/')),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('pixel_spacing_x', models.FloatField(blank=True, null=True)),
                ('pixel_spacing_y', models.FloatField(blank=True, null=True)),
                ('slice_thickness', models.FloatField(blank=True, null=True)),
                ('window_width', models.FloatField(blank=True, null=True)),
                ('window_center', models.FloatField(blank=True, null=True)),
                ('processed_image_cache', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['instance_number'],
            },
        ),
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=100)),
                ('series_number', models.IntegerField(default=0)),
                ('series_description', models.CharField(blank=True, max_length=200)),
                ('modality', models.CharField(max_length=10)),
                ('body_part_examined', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['series_number'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='viewer.dicomimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewer.dicomseries'),
        ),
        migrations.CreateModel(
            name='DicomStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=100, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_id', models.CharField(max_length=100)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_time', models.TimeField(blank=True, null=True)),
                ('study_description', models.TextField(blank=True)),
                ('modality', models.CharField(max_length=10)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='viewer.dicomstudy'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('line', 'Line Measurement'), ('angle', 'Angle Measurement'), ('area', 'Area Measurement')], default='line', max_length=10)),
                ('coordinates', models.JSONField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='px', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='viewer.dicomimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dicomimage',
            unique_together={('series', 'sop_instance_uid')},
        ),
        migrations.AlterUniqueTogether(
            name='dicomseries',
            unique_together={('study', 'series_instance_uid')},
        ),
    ]
