# Generated by Django 5.0 on 2025-07-28 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('letterhead_logo', models.ImageField(blank=True, null=True, upload_to='facility_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='color',
            field=models.CharField(default='#FFFF00', max_length=7),
        ),
        migrations.AddField(
            model_name='annotation',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='bits_allocated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='image_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='photometric_interpretation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='pixel_spacing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='samples_per_pixel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='accession_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='clinical_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='referring_physician',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='measurement',
            name='hounsfield_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='hounsfield_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='hounsfield_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='hounsfield_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[('line', 'Line Measurement'), ('angle', 'Angle Measurement'), ('area', 'Area Measurement'), ('ellipse', 'Ellipse HU Measurement')], default='line', max_length=10),
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('findings', models.JSONField()),
                ('summary', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('highlighted_regions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='viewer.dicomimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.facility'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_study', 'New Study Upload'), ('report_ready', 'Report Ready'), ('ai_complete', 'AI Analysis Complete'), ('system', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.dicomstudy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('finalized', 'Finalized'), ('printed', 'Printed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='viewer.dicomstudy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_id', models.CharField(max_length=100)),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('scheduled_station_ae_title', models.CharField(max_length=16)),
                ('scheduled_procedure_step_start_date', models.DateField()),
                ('scheduled_procedure_step_start_time', models.TimeField()),
                ('modality', models.CharField(max_length=10)),
                ('scheduled_performing_physician', models.CharField(max_length=200)),
                ('procedure_description', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.facility')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.dicomstudy')),
            ],
            options={
                'ordering': ['-scheduled_procedure_step_start_date', '-scheduled_procedure_step_start_time'],
            },
        ),
    ]
