# Generated by Django 4.2.18 on 2025-07-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
    ]
