# Generated by Django 5.0 on 2025-07-29 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_notification_notification_type_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='ae_title',
            field=models.CharField(blank=True, help_text='DICOM AE Title for PACS communication', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to=settings.AUTH_USER_MODEL),
        ),
    ]
