# Generated by Django 5.0 on 2025-07-29 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_facility_ae_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='dicom_port',
            field=models.IntegerField(blank=True, help_text='DICOM C-STORE SCP port automatically assigned for this facility', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ae_title',
            field=models.CharField(blank=True, help_text='DICOM AE Title automatically generated for this facility', max_length=16, null=True, unique=True),
        ),
    ]
