# Generated by Django 4.2.18 on 2025-08-05 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0006_merge_20250804_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict, help_text="User's viewer settings and preferences")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='AttachedStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_dicom_file', models.FileField(blank=True, null=True, upload_to='attached_studies/dicom/')),
                ('external_report_file', models.FileField(blank=True, null=True, upload_to='attached_studies/reports/')),
                ('attachment_type', models.CharField(choices=[('comparison', 'Comparison Study'), ('followup', 'Follow-up Study'), ('baseline', 'Baseline Study'), ('reference', 'Reference Study')], default='comparison', max_length=20)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_description', models.CharField(blank=True, max_length=200)),
                ('modality', models.CharField(blank=True, max_length=10)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes about this attachment')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_studies', to='viewer.dicomstudy')),
                ('previous_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='viewer.dicomstudy')),
            ],
            options={
                'verbose_name': 'Attached Study',
                'verbose_name_plural': 'Attached Studies',
                'ordering': ['-attached_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_mode', models.CharField(choices=[('side_by_side', 'Side by Side'), ('overlay', 'Overlay'), ('toggle', 'Toggle'), ('linked', 'Linked Viewing')], default='side_by_side', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('comparison_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sessions', to='viewer.dicomstudy')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('primary_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_comparisons', to='viewer.dicomstudy')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('primary_study', 'comparison_study', 'created_by')},
            },
        ),
    ]
