# Generated by Django 5.2.4 on 2025-07-28 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewer', '0002_facility_annotation_font_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomSCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ae_title', models.CharField(default='NOCTISVIEW', max_length=16)),
                ('port', models.IntegerField(default=11112)),
                ('host', models.CharField(default='0.0.0.0', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_route_to_worklist', models.BooleanField(default=True)),
                ('storage_path', models.CharField(default='dicom_storage/', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.facility')),
            ],
            options={
                'verbose_name': 'DICOM SCP Server',
                'verbose_name_plural': 'DICOM SCP Servers',
            },
        ),
        migrations.CreateModel(
            name='WorklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('study_instance_uid', models.CharField(max_length=100, unique=True)),
                ('accession_number', models.CharField(blank=True, max_length=100)),
                ('study_date', models.DateField()),
                ('study_time', models.TimeField(blank=True, null=True)),
                ('modality', models.CharField(max_length=10)),
                ('study_description', models.TextField(blank=True)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('referring_physician', models.CharField(blank=True, max_length=200)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dicom_study', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.dicomstudy')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.facility')),
            ],
            options={
                'verbose_name_plural': 'Worklist Entries',
                'ordering': ['-study_date', '-study_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_studies', to=settings.AUTH_USER_MODEL)),
                ('worklist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='worklist.worklistentry')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('worklist_entry', 'assigned_to')},
            },
        ),
    ]
