version: '3.8'

services:
  web:
    build: .
    container_name: noctisview-app
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - static_volume:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=noctisview.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    container_name: noctisview-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=noctisview
      - POSTGRES_USER=noctisuser
      - POSTGRES_PASSWORD=noctispassword
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: noctisview-redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: noctisview-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - ./media:/app/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: